import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100 text-gray-900`}>
        <SidebarProvider>
          <AppSidebar />
          <div className="flex flex-col flex-grow px-8">
            <header className="my-4">Header</header>
            <main className="flex-grow bg-white rounded-xl">
              <SidebarTrigger />
              {children}
            </main>
            <footer className="my-4">Footer</footer>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
